### ISSUE TITLE
requirements for windows?

### ISSUE THREAD

**Issue by eps696** [vlarine/ruGPT2#5]
do you have installation requirements for this repo?

i tried generating texts as shown in `generate_text_yttm_file.sh`, got quite cryptic error:
```
Traceback (most recent call last):
  File "lib/generate_samples.py", line 28, in <module>
    from utils import Timers
  File "F:\_neuro\_work\_todo\_text\rugpt\lib\utils.py", line 25, in <module>
    from fp16 import FP16_Optimizer
  File "F:\_neuro\_work\_todo\_text\rugpt\lib\fp16\__init__.py", line 15, in <module>
    from .fp16util import (
  File "F:\_neuro\_work\_todo\_text\rugpt\lib\fp16\fp16util.py", line 21, in <module>
    import mpu
  File "F:\_neuro\_work\_todo\_text\rugpt\lib\mpu\__init__.py", line 35, in <module>
    from .layers import ColumnParallelLinear
  File "F:\_neuro\_work\_todo\_text\rugpt\lib\mpu\layers.py", line 28, in <module>
    from apex.normalization.fused_layer_norm import FusedLayerNorm as LayerNorm
  File "C:\Users\eps\AppData\Local\Programs\Python\Python35\lib\site-packages\apex\__init__.py", line 18, in <module>
    from apex.interfaces import (ApexImplementation,
  File "C:\Users\eps\AppData\Local\Programs\Python\Python35\lib\site-packages\apex\interfaces.py", line 10, in <module>
    class ApexImplementation(object):
  File "C:\Users\eps\AppData\Local\Programs\Python\Python35\lib\site-packages\apex\interfaces.py", line 14, in ApexImplementation
    implements(IApex)
  File "C:\Users\eps\AppData\Local\Programs\Python\Python35\lib\site-packages\zope\interface\declarations.py", line 650, in implements
    raise TypeError(_ADVICE_ERROR % 'implementer')
TypeError: Class advice impossible in Python3.  Use the @implementer class decorator instead.
```

apex installation completed as following:
Successfully installed PasteDeploy-2.1.0 SQLAlchemy-1.3.15 anykeystore-0.2 apex-0.9.10.dev0 cryptacular-1.5.5 defusedxml-0.6.0 hupper-1.10.2 pbkdf2-1.3 plaster-1.0 plaster-pastedeploy-0.7 pyramid-1.10.4 pyramid-mailer-0.15.1 python3-openid-3.1.0 repoze.sendmail-4.4.1 transaction-3.0.0 translationstring-1.3 velruse-1.1.1 venusian-3.0.0 webob-1.8.6 wtforms-2.2.1 wtforms-recaptcha-0.3.2 zope.deprecation-4.4.0 zope.interface-5.0.1 zope.sqlalchemy-1.3   

windows 10, single geforce 1080, cuda 10.0, cudnn 7.5.0, python 3.5.2, pytorch 1.2.0

**Comment by eps696** [comment]
got through the `apex` issue (had to install from github, not via pip), 
also had to setup `youtokentome==1.0` (current v.1.0.6 has thrown errors),
but got finally stuck at `module 'torch.distributed' has no attribute 'init_process_group'`,
since torch doesn't support dataparallel on windows.

so, is there any chance to run this on windows with single gpu?

**Comment by shabashaash** [comment]
git clone https://www.github.com/nvidia/apex
cd apex
pip install -e ".../apex" --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext"

Try this out.
